/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/demo/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Benchmarks
         * @description List valid completed benchmark reports, newest first.
         */
        get: operations["get_benchmarks_api_v1_demo_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/benchmarks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Benchmark
         * @description Return one regex-validated raw benchmark report.
         */
        get: operations["get_benchmark_api_v1_demo_benchmarks__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/compare/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compare a single FHIR resource through Jev and its rule baseline.
         */
        post: operations["compare_api_v1_demo_compare__module__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the active demo configuration and module prompts.
         */
        get: operations["get_config_api_v1_demo_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decisions
         * @description Return recent decision events in descending sequence order.
         */
        get: operations["get_decisions_api_v1_demo_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/decisions/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Decisions
         * @description Stream replayed or live decision-feed events as server-sent events.
         */
        get: operations["stream_decisions_api_v1_demo_decisions_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fixtures
         * @description List the filtered, allow-listed fixture catalog.
         */
        get: operations["get_fixtures_api_v1_demo_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/fixtures/{fixture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fixture
         * @description Load an allow-listed FHIR resource without constructing user paths.
         */
        get: operations["get_fixture_api_v1_demo_fixtures__fixture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Start the finite labelled-fixture replay pipeline.
         */
        post: operations["run_pipeline_api_v1_demo_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/pipeline/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Pipeline
         * @description Stop the active named pipeline run, if it is still running.
         */
        post: operations["stop_pipeline_api_v1_demo_pipeline__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/detect-notifiable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Notifiable
         * @description Detect reportable disease conditions and return a Flag when confirmed.
         */
        post: operations["detect_notifiable_api_v1_detect_notifiable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Expose Prometheus-compatible counters and histograms.
         */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quality Score
         * @description Return a data-quality decision for a raw FHIR resource.
         */
        post: operations["quality_score_api_v1_quality_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/route-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Bundle
         * @description Route a raw FHIR Bundle to a declared processing category.
         */
        post: operations["route_bundle_api_v1_route_bundle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the API has initialized its configured Jev client.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BenchmarkSummary
         * @description Metadata displayed for a completed benchmark report.
         */
        BenchmarkSummary: {
            /** Dataset */
            dataset: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Jev Model */
            jev_model: string | null;
            /** Mode */
            mode: string;
            /** Name */
            name: string;
        };
        /**
         * BundleRouteRequest
         * @description Request body for routing a FHIR Bundle.
         */
        BundleRouteRequest: {
            /** Bundle */
            bundle: {
                [key: string]: unknown;
            };
        };
        /**
         * BundleRouteResponse
         * @description Structured result returned by the Bundle router.
         */
        BundleRouteResponse: {
            /** Bundle Id */
            bundle_id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Latency Ms */
            latency_ms: number;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
        };
        /**
         * ChoiceResult
         * @description Result of a Jev Choice decision.
         */
        ChoiceResult: {
            /** Choice */
            choice: string;
            /** Confidence */
            confidence: number;
            /** Latency Ms */
            latency_ms: number;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Tokens Used */
            tokens_used: number;
        };
        /**
         * CompareRequest
         * @description A FHIR resource to decide, with an optional fixture id (for ground truth) and overrides.
         */
        CompareRequest: {
            /** Fixture Id */
            fixture_id?: string | null;
            /** Resource */
            resource: {
                [key: string]: unknown;
            };
            /** Resource Type */
            resource_type?: ("Patient" | "Observation") | null;
            thresholds?: components["schemas"]["ThresholdOverrides"] | null;
        };
        /**
         * CompareResponse
         * @description A Jev decision side by side with the rules, ground truth, lane and audit trail.
         */
        CompareResponse: {
            /** Audit Event */
            audit_event: {
                [key: string]: unknown;
            };
            /** Ground Truth */
            ground_truth: {
                [key: string]: unknown;
            } | null;
            /** Jev */
            jev: components["schemas"]["QualityScoreResponse"] | components["schemas"]["BundleRouteResponse"] | components["schemas"]["NotifiableDetectionResponse"];
            /** Jev Decision */
            jev_decision: string;
            /** Jev Raw */
            jev_raw: components["schemas"]["JevCall"][];
            /**
             * Lane
             * @enum {string}
             */
            lane: "auto_accepted" | "routed" | "flagged" | "review";
            /** Lane Reason */
            lane_reason: string;
            /**
             * Module
             * @enum {string}
             */
            module: "quality" | "router" | "notifiable";
            /** Override Applied */
            override_applied: boolean;
            rule: components["schemas"]["RuleDecision"];
            /** Serialized State */
            serialized_state: {
                [key: string]: unknown;
            };
            thresholds: components["schemas"]["Thresholds"];
            /** Tokens Used */
            tokens_used: number;
            verdict: components["schemas"]["Verdict"];
        };
        /**
         * DecisionEvent
         * @description One demo decision as published to the feed; seq is stamped by DecisionFeed.publish.
         */
        DecisionEvent: {
            /** Confidence */
            confidence: number;
            /** Decision */
            decision: string;
            /** Error */
            error?: string | null;
            /** Fixture Id */
            fixture_id: string | null;
            /** Ground Truth Match */
            ground_truth_match: boolean | null;
            /** Jev Latency Ms */
            jev_latency_ms: number;
            /**
             * Lane
             * @enum {string}
             */
            lane: "auto_accepted" | "routed" | "flagged" | "review";
            /** Lane Reason */
            lane_reason: string;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Module
             * @enum {string}
             */
            module: "quality" | "router" | "notifiable";
            /** Resource Reference */
            resource_reference: string;
            /** Run Id */
            run_id: string | null;
            /** Seq */
            seq: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tokens Used */
            tokens_used: number;
        };
        /**
         * DemoConfig
         * @description Demo mode, model, default thresholds, route options and the exact Jev questions.
         */
        DemoConfig: {
            /** Jev Model */
            jev_model: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            /** Questions */
            questions: {
                [key: string]: string;
            };
            /** Route Options */
            route_options: string[];
            thresholds: components["schemas"]["Thresholds"];
        };
        /**
         * FixtureEntry
         * @description One allow-listed fixture with its label, provenance and ground truth.
         */
        FixtureEntry: {
            /** Approved */
            approved: boolean;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "easy" | "hard";
            /** Ground Truth */
            ground_truth: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Module
             * @enum {string}
             */
            module: "quality" | "router" | "notifiable";
            /** Name */
            name: string;
            /** Resource Type */
            resource_type: string;
            /**
             * Source
             * @enum {string}
             */
            source: "unit" | "hard" | "generated" | "demo";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JevCall
         * @description One typed Jev primitive call and its raw result.
         */
        JevCall: {
            /** Options */
            options?: string[] | null;
            /**
             * Primitive
             * @enum {string}
             */
            primitive: "choice" | "score" | "noul";
            /** Question */
            question: string;
            /** Result */
            result: components["schemas"]["ChoiceResult"] | components["schemas"]["ScoreResult"] | components["schemas"]["NoulResult"];
        };
        /**
         * NotifiableDetectRequest
         * @description Request body for detecting a notifiable FHIR Condition.
         */
        NotifiableDetectRequest: {
            /** Condition */
            condition: {
                [key: string]: unknown;
            };
        };
        /**
         * NotifiableDetectionResponse
         * @description Structured result returned by the notifiable-disease detector.
         */
        NotifiableDetectionResponse: {
            /** Condition Code */
            condition_code: string;
            /** Condition Display */
            condition_display: string;
            /** Flag Resource */
            flag_resource: {
                [key: string]: unknown;
            } | null;
            /** Is Notifiable */
            is_notifiable: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Probability */
            probability: number;
            /** Status */
            status: string;
        };
        /**
         * NoulResult
         * @description Result of a Jev Noul decision; probability is P(statement is true).
         */
        NoulResult: {
            /** Answer */
            answer: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Probability */
            probability: number;
            /** Tokens Used */
            tokens_used: number;
        };
        /**
         * PipelineRunRequest
         * @description What to replay: fixture source, modules, pacing, and optional threshold overrides.
         */
        PipelineRunRequest: {
            /**
             * Modules
             * @default [
             *       "quality",
             *       "router",
             *       "notifiable"
             *     ]
             */
            modules: ("quality" | "router" | "notifiable")[];
            /**
             * Rate Per S
             * @default 4
             */
            rate_per_s: number | null;
            /**
             * Source
             * @default unit
             * @enum {string}
             */
            source: "all" | "unit" | "hard" | "generated" | "demo";
            thresholds?: components["schemas"]["ThresholdOverrides"] | null;
        };
        /**
         * PipelineRunResponse
         * @description Acknowledgement of a started run; decisions arrive through the feed.
         */
        PipelineRunResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @constant
             */
            status: "started";
            /** Total */
            total: number;
        };
        /**
         * QualityScoreRequest
         * @description Request body for scoring a FHIR Patient or Observation.
         */
        QualityScoreRequest: {
            /** Resource */
            resource: {
                [key: string]: unknown;
            };
            /** Resource Type */
            resource_type: string;
            /** Threshold */
            threshold?: number | null;
        };
        /**
         * QualityScoreResponse
         * @description Structured result returned by the quality-scoring module.
         */
        QualityScoreResponse: {
            /** Action */
            action: string;
            /** Confidence */
            confidence: number;
            /** Latency Ms */
            latency_ms: number;
            /** Level */
            level: string;
            /** Missing Fields */
            missing_fields: string[];
            /** Nik Confidence */
            nik_confidence: number | null;
            /** Nik Valid */
            nik_valid: boolean | null;
            /** Resource Reference */
            resource_reference: string;
            /** Score */
            score: number;
        };
        /**
         * RuleDecision
         * @description The rule baseline's decision, in the same vocabulary as the Jev decision.
         */
        RuleDecision: {
            /** Decision */
            decision: string;
            /** Nik Valid */
            nik_valid?: boolean | null;
            /** Score */
            score?: number | null;
        };
        /**
         * ScoreResult
         * @description Result of a Jev Score decision.
         */
        ScoreResult: {
            /** Confidence */
            confidence: number;
            /** Latency Ms */
            latency_ms: number;
            /** Level Probabilities */
            level_probabilities?: {
                [key: string]: number;
            } | null;
            /** Score */
            score: number;
            /** Tokens Used */
            tokens_used: number;
        };
        /**
         * ThresholdOverrides
         * @description Optional per-request threshold changes, merged onto the configured defaults.
         */
        ThresholdOverrides: {
            /** Notifiable Confirmed */
            notifiable_confirmed?: number | null;
            /** Notifiable Review */
            notifiable_review?: number | null;
            /** Quality Threshold */
            quality_threshold?: number | null;
            /** Route Confidence Minimum */
            route_confidence_minimum?: number | null;
        };
        /**
         * Thresholds
         * @description Effective decision thresholds for one demo decision; review must not exceed confirmed.
         */
        Thresholds: {
            /** Notifiable Confirmed */
            notifiable_confirmed: number;
            /** Notifiable Review */
            notifiable_review: number;
            /** Quality Threshold */
            quality_threshold: number;
            /** Route Confidence Minimum */
            route_confidence_minimum: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description Whether Jev and the rules matched ground truth; None when there is no ground truth.
         */
        Verdict: {
            /** Jev Correct */
            jev_correct: boolean | null;
            /** Rule Correct */
            rule_correct: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_benchmarks_api_v1_demo_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkSummary"][];
                };
            };
        };
    };
    get_benchmark_api_v1_demo_benchmarks__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_demo_compare__module__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: "quality" | "router" | "notifiable";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_demo_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoConfig"];
                };
            };
        };
    };
    get_decisions_api_v1_demo_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_decisions_api_v1_demo_decisions_stream_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fixtures_api_v1_demo_fixtures_get: {
        parameters: {
            query?: {
                module?: ("quality" | "router" | "notifiable") | null;
                source?: ("unit" | "hard" | "generated" | "demo") | null;
                difficulty?: ("easy" | "hard") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fixture_api_v1_demo_fixtures__fixture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_api_v1_demo_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_pipeline_api_v1_demo_pipeline__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_notifiable_api_v1_detect_notifiable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotifiableDetectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifiableDetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quality_score_api_v1_quality_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_bundle_api_v1_route_bundle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleRouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleRouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
}
